spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Kishore@1998
    url: jdbc:mysql://localhost:3306/book_store_app
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    
server:
  port: 8010
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
